Output demo_trunc.gif

Set FontSize 12
Set Width 450
Set Height 500

Hide
Type "go run main.go" 
Enter 1
Show

Right @200ms 3 Enter @200ms
Left @200ms 1 Enter @200ms
Right @200ms 2 Enter @200ms
Left @200ms 1 Enter @200ms
Right @200ms 2 Enter @200ms
Right @200ms 1 Enter @200ms
Left @200ms 2 Enter @200ms
Enter @400ms
Right @200ms 1 Enter @200ms
Enter @400ms
Left @200ms 2 Enter @200ms
Right @200ms 2 Enter @200ms

Sleep 1s
